#!/bin/bash

title=$1
filename="${title// /_}"
url=$2

sourcefile="Solutions/$filename.js"
echo '/**' >> $sourcefile
echo " * $title" >> $sourcefile
echo " * $url" >> $sourcefile
echo ' */' >> $sourcefile

testfile="test/$filename.test.js"
echo "var test = require('../$sourcefile');" >> $testfile
echo "require('should');" >> $testfile
echo "" >> $testfile
echo "describe('$title', function() {" >> $testfile
echo "    it('should work', function() {" >> $testfile
echo "    });" >> $testfile
echo "});" >> $testfile
