#!/bin/bash

fswatch Solutions | 
while read -r line
do
	filename=$(basename $line)
	extension="${filename##*.}"
	filename="${filename%.*}"
	testfile=test/"$filename.test.$extension"
    if [ -f $testfile ];
    then
        mocha $testfile
    fi
done 
